name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev
      - name: Install python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q --maxfail=1

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t floodmapper:ci .
